@url = http://localhost:4400
@urlprod = 
GET http://localhost:4400/photosapi

###

GET http://localhost:4400/photosapi/5

###
GET http://localhost:4400/photos

###
POST {{url}}/login 
Content-Type: application/json

{
    "email": "john@vanarts.com",
    "password": "654321"
}

###
POST {{url}}/register
Content-Type: application/json

{
    "email": "info@email.com",
    "password": "1234",
    "first_name": "Manny",
    "last_name": "Brown"
}

### 
POST {{url}}/signup
Content-Type: application/json

{
    "email": "asdfasf",
    "password": "123"
}

###
PUT {{url}}/updateUser
Content-Type: application/json

{
    "userID": "1",
    "email": "kyle@vanarts.com",
    "password": "654321"
}

###
GET {{url}}/user/10

###
DELETE {{url}}/deleteuser/9

###
POST {{url}}/textarea
Content-Type: application/json

{
    "text": "text from the server"
}

###
GET {{url}}/posts

###
POST {{url}}/posts
Content-Type: application/json

{
    "newpost": "testing from TEST API",
    "thumbnail": "image1.png"
}


###
GET http://localhost:4400/photos

###
POST http://localhost:4400/photos
Content-Type: application/json

{
    "albumId_fromC": 1,
    "title_fromC": "test Title",
    "url_fromC": "sittingbridge.jpg",
    "tn_fromC": "tn_sittingbridge.jpg"
}

###
POST http://localhost:4400/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
    
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file_fromC"; filename="sittingbridge.jpg" 
Content-Type: image/png

< ./sittingbridge.jpg"
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 
GET http://localhost:4400/photos/26

###
DELETE http://localhost:4400/photos/15